Crazy-Crew/CrazyCrates

src/main/java/me/badbones69/crazycrates/api/objects/ItemBuilder.java
This makes this part of the plugin compatible with 1.14 and gets rid of deprecated api.
Tested on 1.13.2
=> Switch over from durability(short) to damage (int)

plugin/src/main/java/me/badbones69/crazycrates/controllers/CrateControl.java
=> Add pickup protection during crate open.

plugin/pom.xml, plugin/src/main/java/me/badbones69/crazycrates/Methods.java, plugin/src/main/java/me/badbones69/crazycrates/api/CrazyCrates.java, plugin/src/main/java/me/badbones69/crazycrates/api/objects/Crate.java, plugin/src/main/java/me/badbones69/crazycrates/commands/CCCommand.java, plugin/src/main/java/me/badbones69/crazycrates/controllers/CrateControl.java, plugin/src/main/java/me/badbones69/crazycrates/controllers/GUIMenu.java, plugin/src/main/java/me/badbones69/crazycrates/cratetypes/CSGO.java, plugin/src/main/java/me/badbones69/crazycrates/cratetypes/Cosmic.java, plugin/src/main/java/me/badbones69/crazycrates/cratetypes/Roulette.java, plugin/src/main/java/me/badbones69/crazycrates/cratetypes/War.java, plugin/src/main/java/me/badbones69/crazycrates/cratetypes/Wheel.java, pom.xml
Sanitize string format in order to fix CC not detecting inventories as crate inventories due to MC messing around with the order of cformatting codes.
=> Use codemc for dependencies and nms, sanitize string format

plugin/pom.xml, plugin/src/main/java/me/badbones69/crazycrates/api/CrazyCrates.java, plugin/src/main/java/me/badbones69/crazycrates/multisupport/Version.java, pom.xml, v1_16_R3/pom.xml, v1_16_R3/src/main/java/me/badbones69/crazycrates/multisupport/nms/v1_16_R3/NMS_v1_16_R3.java, v1_16_R3/src/main/java/me/badbones69/crazycrates/multisupport/nms/v1_16_R3/StructureService.java
Did basic testing and works just fine.
Doubt there are any issues.
=> 1.16.4 (1_16_R3) support

plugin/src/main/java/me/badbones69/crazycrates/api/CrazyCrates.java, plugin/src/main/java/me/badbones69/crazycrates/api/events/PlayerReceiveKeyEvent.java, plugin/src/main/java/me/badbones69/crazycrates/commands/CCCommand.java, plugin/src/main/java/me/badbones69/crazycrates/cratetypes/Cosmic.java
Added getHandlerList method for PlayerReceiveKeyEvent
PlayerReceiveKeyEvent now supports getAmount which return amount of keys received by event
=> PlayerReceiveKeyEvent - Changes

api/pom.xml, plugin/pom.xml, plugin/src/main/java/me/badbones69/crazycrates/api/CrazyCrates.java, plugin/src/main/java/me/badbones69/crazycrates/multisupport/Version.java, pom.xml, v1_17_R1/pom.xml, v1_17_R1/src/main/java/me/badbones69/crazycrates/multisupport/nms/v1_17_R1/NMS_v1_17_R1.java, v1_17_R1/src/main/java/me/badbones69/crazycrates/multisupport/nms/v1_17_R1/StructureService.java
The 1.17 module gets compiled on Java 16 due to it being needed.
Edit:
Download: https://discord.com/channels/182615261403283459/196107841449361408/855723798724608030
Direct: https://cdn.discordapp.com/attachments/196107841449361408/855723798514630656/CrazyCratesv1.10.1.jar
=> Update to 1.17

api/pom.xml, plugin/pom.xml, plugin/src/main/java/me/badbones69/crazycrates/api/CrazyCrates.java, plugin/src/main/java/me/badbones69/crazycrates/multisupport/Version.java, pom.xml, v1_17_R1/pom.xml, v1_17_R1/src/main/java/me/badbones69/crazycrates/multisupport/nms/v1_17_R1/NMS_v1_17_R1.java, v1_17_R1/src/main/java/me/badbones69/crazycrates/multisupport/nms/v1_17_R1/StructureService.java
Reverts badbones69/Crazy-Crates#363
=> Revert "Revert "Update to 1.17""

plugin/pom.xml
Previously it would miss some files that should also be relocated too.
=> Update shade plugin and relocate rest of nbtapi

plugin/src/main/java/me/badbones69/crazycrates/controllers/BrokeLocationsControl.java
=> Fix holograms not showing up

api/pom.xml, plugin/pom.xml, plugin/src/main/java/me/badbones69/crazycrates/api/CrazyCrates.java, plugin/src/main/java/me/badbones69/crazycrates/multisupport/Version.java, pom.xml, v1_18_R1/pom.xml, v1_18_R1/src/main/java/me/badbones69/crazycrates/multisupport/nms/v1_18_R1/NMS_v1_18_R1.java, v1_18_R1/src/main/java/me/badbones69/crazycrates/multisupport/nms/v1_18_R1/StructureService.java
=> Add 1.18 support

build.gradle.kts
Dead repo and any plugin that uses it supports placeholderapi.
=> Remove MVdWPlaceholderAPI

src/main/java/com/badbones69/crazycrates/api/objects/Crate.java
Fix adding an extra page when having up to 9 slots less than maxSlots.
=> Fix Preview Bug

src/main/java/com/badbones69/crazycrates/api/CrazyManager.java, src/main/java/com/badbones69/crazycrates/api/enums/Permissions.java, src/main/java/com/badbones69/crazycrates/api/objects/Crate.java, src/main/java/com/badbones69/crazycrates/commands/subs/CrateBaseCommand.java, src/main/resources/crates/CosmicCrateExample.yml, src/main/resources/crates/CrateExample.yml, src/main/resources/crates/QuadCrateExample.yml, src/main/resources/crates/QuickCrateExample.yml
Basically stole the method from QuickCrate. (Only works for virtual keys for now)
Made this a while back due to a player wanting it, but did not know if it would create any dupes or problems and assumed that it would cause lag if they have too many keys.
=> /cc mass-open <amount>

paper/src/main/java/com/badbones69/crazycrates/api/CrazyManager.java
Use `quoteReplacement()` for the %reward% placeholder to fix the error that it caused when having $ in the reward name.
=> Fix %reward% with $ in the name.

paper/src/main/java/com/badbones69/crazycrates/Methods.java
Fix the error caused by $ being used in `.replaceAll` with %prefix%.
=> Fix $ in %prefix%

gradle/libs.versions.toml
Fix why the plugin could not compile.
=> Bump cmi lib

build.gradle.kts, core/build.gradle.kts, paper/build.gradle.kts, paper/src/main/resources/plugin.yml
* Removed hangar as it doesn't work at the moment.
* Fixed a plugin.yml issue
* Fixed a relocation issue with shadowJar
=> Fixes a stupid boot error

README.md, build.gradle.kts, paper/src/main/java/com/badbones69/crazycrates/paper/api/CrazyManager.java, paper/src/main/java/com/badbones69/crazycrates/paper/api/objects/ItemBuilder.java, paper/src/main/resources/crates/CosmicCrateExample.yml, paper/src/main/resources/crates/CrateExample.yml, paper/src/main/resources/crates/QuadCrateExample.yml, paper/src/main/resources/crates/QuickCrateExample.yml
* Updated README
* Fixed a placeholder issue
=> Add the ability to change damage on an item.

build.gradle, common/src/main/java/us/crazycrew/crazycrates/common/config/types/Config.java, gradle.properties, gradle/libs.versions.toml, paper/run/server.properties, paper/src/main/java/com/badbones69/crazycrates/paper/api/objects/ItemBuilder.java, paper/src/main/java/us/crazycrew/crazycrates/paper/listeners/menus/CrateAdminListener.java
* Updated a section of the itembuilder to better support custom items.
* A simple fix in the admin menu to prevent getting keys if clicking already existing keys in inventory.
=> Fix a few minor annoyances

paper/src/main/java/com/badbones69/crazycrates/listeners/CrateControlListener.java
=> Fix dummy event handling

paper/src/main/java/com/badbones69/crazycrates/commands/CommandManager.java, paper/src/main/java/com/badbones69/crazycrates/commands/crates/types/BaseCommand.java, paper/src/main/java/com/badbones69/crazycrates/commands/crates/types/admin/keys/CommandGive.java, paper/src/main/java/com/badbones69/crazycrates/commands/crates/types/admin/keys/CommandOpen.java, paper/src/main/java/com/badbones69/crazycrates/commands/crates/types/admin/keys/CommandTake.java
/crazycrates forceopen got merged with /crazycrates open-others, You simply need to specific "free" or "f" for the keytype while typing the command.
=> Fix a few bugs and update commands

src/main/java/com/badbones69/crazycrates/tasks/crates/types/WheelCrate.java
Makes the animation go around instead of top to bottom.
=> Fix Wheel Crate

src/main/java/com/badbones69/crazycrates/tasks/crates/CrateManager.java
Change Roulette crate back to the correct inventory size.
=> Fix Roulette Crate
