- src/me/BadBones69/CrazyCrates/SettingsManager.java
One of the bugs that we came across on our server was that if there were any files in the Crates folder, including lock files, this plugin would try to pull them in as a type of crate, leading to unpredictable behavior. This aims to fix that issue.
> Modified Crate File Checker to ignore files which don't end in .yml

- src/main/java/me/badbones69/crazycrates/controllers/Preview.java
Someone typed the number 7 instead of the character &, causing the item to appear in the game like "Menu 77"
> Replaced a wrongly put chatcolor character

- src/main/java/me/badbones69/crazycrates/api/CrazyCrates.java
- src/main/java/me/badbones69/crazycrates/api/objects/ItemBuilder.java
This allows to hide all flags. For example armor and unbreakable
Before: http://prntscr.com/nlsjvw
After: http://prntscr.com/nlsk60
Tested on 1.13.2
Configs without the option set, resulting in no Flags hidden
> Add support for hiding ItemFlags

- src/main/resources/Crates/Basic.yml
- src/main/resources/Crates/Classic.yml
- src/main/resources/Crates/Crazy.yml
- src/main/resources/Crates/Galactic.yml
Moved all comments to basic and only left cosmic specific comments in cosmic
The old config lines right behind the values made them kinda hard to see/read (At least in some editors, for example Notepad++)
Added remaining nodes to all configs. Missing nodes confused me as I copy pasted
some sections and was wondering about missing nodes.
I am aware that you can remove nodes if you wish, but most people are copy pasting or start editing existing configs and might wondering about not seeing some of them. Or they don't even know they exist.
Thats purely a design thing and you might think different about it, so no worries if you don't agree
> Reformat comments in example crates + added missing nodes

- plugin/src/main/java/me/badbones69/crazycrates/api/CrazyCrates.java
- plugin/src/main/java/me/badbones69/crazycrates/api/objects/Crate.java
- plugin/src/main/java/me/badbones69/crazycrates/controllers/Preview.java
- plugin/src/main/resources/Crates1.12.2-Down/Basic.yml
- plugin/src/main/resources/Crates1.12.2-Down/Classic.yml
- plugin/src/main/resources/Crates1.12.2-Down/Crazy.yml
- plugin/src/main/resources/Crates1.12.2-Down/Galactic.yml
- plugin/src/main/resources/Crates1.13-Up/Basic.yml
- plugin/src/main/resources/Crates1.13-Up/Classic.yml
- plugin/src/main/resources/Crates1.13-Up/Crazy.yml
- plugin/src/main/resources/Crates1.13-Up/Galactic.yml
Defaults to 6 lines (double chest)
Can be 3 to 6 lines including the header/bottom
Fixes long standing issue that when disabling the glass border one line was empty
Disabling the glass border now also disables the bottom border
> Let users customize the preview lines per crate config

- api/src/main/java/me/badbones69/crazycrates/multisupport/nms/NMSSupport.java
- plugin/pom.xml
- plugin/src/main/java/me/badbones69/crazycrates/Main.java
- plugin/src/main/java/me/badbones69/crazycrates/Methods.java
- plugin/src/main/java/me/badbones69/crazycrates/cratetypes/CrateOnTheGo.java
- v1_10_R1/src/main/java/me/badbones69/crazycrates/multisupport/nms/v1_10_R1/NMS_v1_10_R1.java
- v1_11_R1/src/main/java/me/badbones69/crazycrates/multisupport/nms/v1_11_R1/NMS_v1_11_R1.java
- v1_12_R1/src/main/java/me/badbones69/crazycrates/multisupport/nms/v1_12_R1/NMS_v1_12_R1.java
- v1_13_R2/src/main/java/me/badbones69/crazycrates/multisupport/nms/v1_13_R2/NMS_v1_13_R2.java
- v1_14_R1/src/main/java/me/badbones69/crazycrates/multisupport/nms/v1_14_R1/NMS_v1_14_R1.java
- v1_8_R3/src/main/java/me/badbones69/crazycrates/multisupport/nms/v1_8_R3/NMS_v1_8_R3.java
- v1_9_R1/src/main/java/me/badbones69/crazycrates/multisupport/nms/v1_9_R1/NMS_v1_9_R1.java
- v1_9_R2/src/main/java/me/badbones69/crazycrates/multisupport/nms/v1_9_R2/NMS_v1_9_R2.java
Fixes cc additem on 1.8.8
Removes dirty method of getItemInHand from Methods
Reuse Random. Only use new Random on class init if at all
Adds paperlib exclusion to WE dep
> Add getItemInMainHand Method to NMS Class

- plugin/src/main/java/me/badbones69/crazycrates/api/CrazyCrates.java
- plugin/src/main/java/me/badbones69/crazycrates/controllers/GUIMenu.java
Pretty weird that you can use these properties in `crate config` but not in `GUI-Customizer` config.
I had tested and work pretty great, here is the config example:
```yaml
Slot:2, Item:DIAMOND_SWORD:4, Unbreakable-Item:true, Hide-Item-Flags:true, Name:&8
```
> Make GUIMenu can add Unbreakable and HideItemFlags

- plugin/src/main/java/me/badbones69/crazycrates/api/events/PlayerReceiveKeyEvent.java
Adding the getHandlerList() method fixes this error: http://prntscr.com/103t7ki
> Update PlayerReceiveKeyEvent.java (Adding getHandlerList(), event doesnt work at all without it)

- plugin/pom.xml
- plugin/src/main/java/me/badbones69/crazycrates/Methods.java
- plugin/src/main/java/me/badbones69/crazycrates/api/CrazyCrates.java
- plugin/src/main/java/me/badbones69/crazycrates/cratetypes/CrateOnTheGo.java
- plugin/src/main/java/me/badbones69/crazycrates/cratetypes/QuickCrate.java
Fixes #381 by modifying the isSimilar method to include a check for NBT data, which was previously not there. Now, if they rename their item or modify the item's lore, it will still count as that type of key and will be used when a play shifts + right-clicks a quick crate. As far as my testing, this does not break any other types of crates, although testing was somewhat limited.
I also updated the plugin pom.xml to use the updated repositories for PlaceholderAPI & MVdWPlaceholderAPI, as well as the updated versions. I don't believe this will cause any issues.
> Fix Dupe Glitch & Update pom.xml

- README.md
For some reason, the download link for spigot was pointing towards CrazyEnchantments instead of CrazyCrates
> Fix incorrect spigot download link.

- build.gradle.kts
Update PaperMC to 1.19.2 and DecentHolograms to 2.7.2. 
I tested and everything appears to still work correctly.
> Update Paper & DecentHolograms

- src/main/java/com/badbones69/crazycrates/api/enums/Permissions.java
- src/main/java/com/badbones69/crazycrates/commands/subs/CrateBaseCommand.java
- src/main/resources/messages.yml
- Added new permission "crazycrates.command.exclude.player.giveall" which will exclude you from getting crates from /cc giveAll.
- Added missing periods in some permission descriptions.
- Fixed the permission link in messages.yml so that newer users can get a working link to the permissions page.
Had no clue what the permission name should be and can make changes if needed.
Not sure if it should also tell them who (did/did not) get keys or amount of players that (did/did not) get them.
> Add Permission to prevent keys from giveAll & Fix permission link

- src/main/java/com/badbones69/crazycrates/commands/subs/CrateBaseCommand.java
In response to an issue I reported on discord of knockback being applied when disabled and in the crates GUI ([Discord message](https://discord.com/channels/182615261403283459/196107841449361408/1045827979185504356)).
Added an If statement to knockback applied in the `openCrate` function.
```java
if (config.getBoolean("Settings.KnockBack")) CrateControlListener.knockBack(player, player.getTargetBlock(null, 1).getLocation());
```
I tested and it is working on my Paper 1.19.2 server.
> Fix applying knockback when disabled and in GUI

- src/main/java/com/badbones69/crazycrates/api/CrazyManager.java
- src/main/java/com/badbones69/crazycrates/api/enums/Permissions.java
- src/main/java/com/badbones69/crazycrates/commands/subs/CrateBaseCommand.java
- src/main/resources/plugin.yml
A command that gives players a random key out of all of the crates that you have. 
Specify a number higher than 1 to give them more than 1 of said key.
Command: `/cc give-random <virtual/physical> <amount> <player>`
Permission node: `crazycrates.command.admin.giverandomkey`
> /cc give-random

- build.gradle.kts
When the next modrinth release is ready, It will now push the proper jar automatically.
> Fix modrinth publish task

- paper/src/main/java/com/badbones69/crazycrates/cratetypes/QuickCrate.java
- paper/src/main/resources/crates/QuickCrateExample.yml
Add in the same value as from /cc mass-open to be used for the max amount that can be opened at a time with QuickCrate as they cause basically the same amount of lag.
> Max-Mass-Open for QuickCrate

- build-logic/build.gradle.kts
- build-logic/src/main/kotlin/crazycrates.root-conventions.gradle.kts
- build-logic/src/main/kotlin/task/ReleaseWebhook.kt
- build-logic/src/main/kotlin/task/WebhookExtension.kt
- build.gradle.kts
To configure make sure to add the `webhook` extension to the root `build.gradle.kts` and the webhook URL into the `gradle.properties` in the **user**'s `.gradle` folder under the key `discord.webhook.url`, don't put it in the project, keep it private.
To run simply run the task `releaseWebhook`, feel free to rename it in the root conventions plugin.
> feature: Simple Discord webhook task

- paper/src/main/java/com/badbones69/crazycrates/paper/api/CrazyManager.java
- paper/src/main/java/com/badbones69/crazycrates/paper/api/enums/settings/Messages.java
- paper/src/main/resources/messages.yml
- paper/src/main/resources/plugin.yml
- `No-Crate-Permission:`
- `crazycrates.open.<crateName>` 
- `crazycrates.open.*` default: true
The current permission check and enum are based on command usage, but may need to be revised to better align with the rest of the code. Therefore permission checks were used the way that they currently are.
> Crate Open Permission

- paper/src/main/java/com/badbones69/crazycrates/paper/cratetypes/Cosmic.java
- paper/src/main/resources/plugin.yml
Remove the magic number that caused the cosmic-crate type to always break when players set the amount to less than 4.
> Remove Magic Number

- gradle.properties
- paper/src/main/java/com/badbones69/crazycrates/api/objects/Crate.java
- paper/src/main/java/com/badbones69/crazycrates/api/objects/Prize.java
The issue was I was using a method that got the `DisplayName` of the item which is only for previews. If the display name of 2 prizes were exactly the same. It would just get confused and not give prizes correctly.
getPrizeNumber() returns `1` which is what we want when picking prizes.
This is likely the last update for 1.20.4 unless another bug shows up.
```yml
Crate:
Prizes:
1:
DisplayName: "&cAn example of a Player Head!"
```
> Fixes an issue where prizes were picked incorrectly.

- CHANGELOG.md
- build.gradle.kts
- gradle.properties
- paper/run/server.properties
- paper/src/main/java/com/badbones69/crazycrates/api/objects/Crate.java
- paper/src/main/java/com/badbones69/crazycrates/api/objects/Prize.java
This pull request deserializes and re-serializes the lore when read/writing from configuration
It builds the item stack if DisplayLore is found, converts the lore to components and then sets it to the item meta then creates a new itembuilder object then carries on like normal.
> Lores are stupid

- CHANGELOG.md
- HISTORY.md
- src/main/java/com/badbones69/crazycrates/api/builders/CrateBuilder.java
- src/main/java/com/badbones69/crazycrates/config/impl/messages/CrateKeys.java
- src/main/java/com/badbones69/crazycrates/listeners/crates/CrateOpenListener.java
- src/main/java/com/badbones69/crazycrates/tasks/crates/CrateManager.java
Changed crate open permission over to being a deny open permission. This change should simplify how crate permissions are handled by reducing it to a single permission per crate that is more self-explanatory.
With this change, OPed players will by default not be able to open crates due to them having all permissions.
Currently, I am not sure if I should make it never deny OPed players from opening crates, or if it should be left as is.
> Replace crate open permission with deny open permission

- src/main/java/com/badbones69/crazycrates/api/enums/Permissions.java
Changes the default to false so that OPed players by default do not have it. This will alter the default behaviour for OPed players so that they receive keys from giveAll.
> Fix exclude.giveAll Default

- paper/src/main/java/com/badbones69/crazycrates/paper/api/objects/Crate.java
Instead of always selecting the first prize of all tiers, pick a random one instead.
> Fix Tier Prize Selection
